# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f818978009a8291d2c1b9427134546a73db0ead06ffacb26da8c4c2b3943f447beb3e3e56337a48dbe8e6cc2237f0254ddbe5b36339c40e947d56e6dbb691b4

test:
  secret_key_base: fe2be148a0900617c280b8fa0f0278a6203ade0e02a3c093ad6b5c9fceaf916621790aca346af35cbaced4ac0933df2297036f71617e942506a12cf507c8fe4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
